// projectsData.jsx — extended case-study data for the interactive portfolio
const PROJECTS_FULL = [
  {
    id: 'car-marketplace-db',
    emoji: '🗃️',
    category: 'SQL & Database',
    date: 'Jan 2026',
    readTime: '15 min read',
    title: 'Building a Relational Database for a Used Car Marketplace',
    excerpt: 'Final Project — SQL & Relational Database Course, Pacmann Academy. Designed and implemented a normalized relational schema, covering entity relationships, constraints, and query optimization.',
    tags: ['SQL', 'Python', 'Database'],
    type: 'article',
    cardSize: 'tall',
    stats: [
      { label: 'Tables', value: '14' },
      { label: 'Indexes', value: '22' },
      { label: 'Normal form', value: '3NF' },
    ],
    sections: [
      { heading: 'Context', body: 'Used-car marketplaces juggle listings, dealers, buyers, inspections, and financing in one place. A flat spreadsheet drowns in duplicates within weeks. The final project for the Pacmann SQL course asked us to design a schema that handled all of this while staying fast under query load.' },
      { heading: 'Schema approach', body: 'Fourteen tables in 3NF, centered on three facts: a listing, a transaction, and an inspection. Reference data (makes, models, trims, dealers, locations) split into dimensions. Every foreign key constrained, every price stored in minor units, every timestamp UTC.' },
      { heading: 'Query performance', body: 'Composite indexes on (status, posted_at) for the feed, (zip, make_id) for local search, (dealer_id, sold_at) for revenue reports. A seed of 1M rows runs the "cars near me under $15k" query in 38ms on a laptop Postgres.' },
      { heading: 'What I would change', body: 'Replace the tags varchar column with a proper many-to-many. Use generated columns for the monthly payment estimate. Move inspection photos to object storage instead of the JSONB blob hack.' },
    ],
    links: [{ label: 'Read on Medium', href: '#' }, { label: 'GitHub', href: '#' }],
  },
  {
    id: 'olist-dwh-design',
    emoji: '🏪',
    category: 'Data Warehouse',
    date: 'Jan 2026',
    readTime: '6 min read',
    title: 'Data Warehouse Design for Olist E‑Commerce Platform',
    excerpt: 'A step-by-step approach to designing a data warehouse for Brazil\'s largest online marketplace, applying Kimball methodology with star schema architecture.',
    tags: ['Database', 'SQL'],
    type: 'article',
    cardSize: 'short',
    stats: [
      { label: 'Fact tables', value: '5' },
      { label: 'Dimensions', value: '9' },
      { label: 'Grain', value: 'Order item' },
    ],
    sections: [
      { heading: 'Goal', body: 'Unify Olist\'s transactional data into a warehouse that answers three questions: what sells, who sells it best, and where delays happen. Star schema with conformed dimensions so dashboards don\'t fight each other.' },
      { heading: 'Modeling decisions', body: 'Grain is a single order item — not the order — because one order can mix sellers with wildly different fulfillment speeds. Date dimension generated for 2016–2030. Customer dimension uses SCD Type 2 on state and city so historical reports stay honest.' },
      { heading: 'Trade-offs', body: 'Denormalized product hierarchy (category → subcategory → leaf) into one dimension for BI speed; accepted the update churn. Kept payment methods as a bridge table to preserve split payments.' },
    ],
    links: [{ label: 'Read on Medium', href: '#' }],
  },
  {
    id: 'aljabbar-hedonic',
    emoji: '🕌',
    category: 'GIS & Urban Planning',
    date: 'May 2024',
    readTime: 'Bachelor Thesis',
    title: 'Hedonic Pricing Analysis of Land Value Changes Near Al‑Jabbar Mosque',
    excerpt: 'Identified changes in land prices following the development of Al-Jabbar Mosque in Gedebage District, Bandung using the Hedonic Pricing Method.',
    tags: ['GIS', 'Urban'],
    type: 'thesis',
    cardSize: 'tall',
    stats: [
      { label: 'Parcels sampled', value: '412' },
      { label: 'Radius', value: '3 km' },
      { label: 'R²', value: '0.71' },
    ],
    sections: [
      { heading: 'Research question', body: 'Did the opening of Al-Jabbar Mosque in Gedebage measurably shift land prices in the surrounding district, and if so, how does the effect decay with distance?' },
      { heading: 'Method', body: 'Hedonic Pricing Model regressing listed land price on distance-to-mosque, road accessibility, parcel width, and zoning class. Prices pulled from 412 listings spanning pre- and post-opening periods. Distance rings at 500m, 1km, 2km, 3km.' },
      { heading: 'Finding', body: 'Parcels within 1km of the mosque saw a 23% average price lift after opening, controlling for road class and zoning. The effect decays to near zero beyond 2.5km. The thesis defended in May 2024 at Institut Teknologi Bandung.' },
      { heading: 'Limitation', body: 'Listed prices ≠ transacted prices. Without a deed registry, the estimate likely overshoots actual lift by 10–15% based on comparable Indonesian market studies.' },
    ],
    links: [{ label: 'Thesis PDF', href: '#' }],
  },
  {
    id: 'citibike-analysis',
    emoji: '🚲',
    category: 'Data Science',
    date: 'Feb 2025',
    readTime: 'Article',
    title: 'Uncovering NYC Bike‑Share Patterns',
    excerpt: 'Analyzed 2.1 million NYC Citi Bike trips from February 2024 using Python, geospatial analysis, and statistical modeling.',
    tags: ['Python', 'GIS', 'Urban'],
    type: 'article',
    cardSize: 'medium',
    stats: [
      { label: 'Trips', value: '2.1M' },
      { label: 'Stations', value: '2,056' },
      { label: 'R² (duration)', value: '0.68' },
    ],
    sections: [
      { heading: 'Dataset', body: 'February 2024 Citi Bike trip records — 2.1 million rides across 2,056 stations. Paired with NYC DOT weather, bike-lane geometry, and subway-stop points for context.' },
      { heading: 'Patterns that surfaced', body: 'Weekday commutes dominate — two sharp peaks at 8am and 6pm, almost entirely from Manhattan residential stations to Midtown. Weekends invert: Brooklyn→Manhattan trips at park scale, longer durations, more leisurely pace. Rain cuts volume 34%.' },
      { heading: 'Model', body: 'Linear regression on trip duration using weather, time-of-day, origin neighborhood density, and bike-lane coverage of the route. R² = 0.68. Bike-lane coverage was the single largest non-weather predictor.' },
    ],
    links: [{ label: 'Read on Medium', href: '#' }, { label: 'GitHub', href: '#' }],
  },
  {
    id: 'citibike-code',
    emoji: '📊',
    category: 'GitHub Repository',
    date: 'Feb 2025',
    readTime: 'Source Code',
    title: 'NYC Citi Bike Analysis — Python Codebase',
    excerpt: 'Full Python codebase: 2.1M trip records, station-level geospatial mapping with GeoPandas & Folium, trip duration regression.',
    tags: ['Python', 'GIS', 'Urban', 'GitHub'],
    type: 'github',
    cardSize: 'short',
    stats: [
      { label: 'Commits', value: '47' },
      { label: 'Notebooks', value: '6' },
      { label: 'Stars', value: '12' },
    ],
    sections: [
      { heading: 'What\'s inside', body: 'Six Jupyter notebooks walking from raw Citi Bike CSVs to the final regression. GeoPandas for station geometry, Folium for interactive maps, scikit-learn for the duration model. All deterministic — seeds pinned.' },
      { heading: 'Reproducibility', body: 'Makefile target `make reproduce` downloads the raw files, runs every notebook, and regenerates the figures. Takes about 12 minutes on a modern laptop.' },
    ],
    links: [{ label: 'GitHub repository', href: '#' }],
  },
  {
    id: 'olist-dimensional',
    emoji: '🏗️',
    category: 'GitHub Repository',
    date: 'Jan 2026',
    readTime: 'Source Code',
    title: 'Olist Data Warehouse — Dimensional Modeling',
    excerpt: 'Production-ready star schema DWH using Kimball methodology. Implements 5 fact table types with conformed dimensions in PostgreSQL.',
    tags: ['Database', 'SQL', 'GitHub'],
    type: 'github',
    cardSize: 'medium',
    stats: [
      { label: 'DDL lines', value: '1,842' },
      { label: 'Fact types', value: '5' },
      { label: 'Postgres', value: '15+' },
    ],
    sections: [
      { heading: 'Scope', body: 'Every DDL file needed to stand up the Olist warehouse: schemas, tables, constraints, indexes, and the seed scripts that populate the date and time dimensions. Runs on vanilla Postgres 15 — no extensions required.' },
      { heading: 'Fact table types', body: 'Transactional (order_item), periodic snapshot (daily_inventory), accumulating snapshot (order_lifecycle), factless (page_view), and aggregate (monthly_sales_by_category). All keyed off the same conformed dimensions.' },
    ],
    links: [{ label: 'GitHub repository', href: '#' }],
  },
  {
    id: 'olist-elt',
    emoji: '⚙️',
    category: 'GitHub Repository',
    date: 'Feb 2026',
    readTime: 'Source Code',
    title: 'Olist Data Warehouse — ELT Pipeline',
    excerpt: 'End-to-end ELT pipeline with SCD Type 1 & 2 logic, Luigi-orchestrated daily ingestion, PostgreSQL star schema, and error alerting.',
    tags: ['Database', 'SQL', 'Python', 'GitHub'],
    type: 'github',
    cardSize: 'tall',
    stats: [
      { label: 'Tasks', value: '38' },
      { label: 'Runtime', value: '~14 min' },
      { label: 'Freshness', value: 'Daily' },
    ],
    sections: [
      { heading: 'Pipeline', body: 'Luigi DAG with 38 tasks covering extract, stage, conform, load, and validate. Each stage is idempotent and atomic — a mid-run failure rolls back cleanly. Raw files land in object storage; staging and warehouse live in Postgres.' },
      { heading: 'SCD handling', body: 'Type 1 for sellers and product categories (history not valuable). Type 2 for customers — new row + closed effective window when address or segment changes. All SCD work happens in SQL, not Python, to keep logic close to the data.' },
      { heading: 'Alerting', body: 'Failed tasks post to a Slack webhook with run ID, failed task, and upstream dependency state. Row-count anomalies (>3σ from 30-day mean) also trigger alerts even on successful runs.' },
    ],
    links: [{ label: 'GitHub repository', href: '#' }],
  },
];

window.PROJECTS_FULL = PROJECTS_FULL;
